app1/urls.py
from app1.views import *

from django.urls import path

app_name='something'

urlpatterns=[
    path('sunita/',sunita,name='sunita'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='nothing'

urlpatterns=[
    path('anita/',anita,name='anita'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def sunita(request):
    return render(request,'sunita.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def anita(request):
    return render(request,'anita.html')

templates/anita.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hi sunita...Iam Fine,Wt abt u?</h1>
        <h1>Iam cmg to home by nextweek</h1>
        <a href="{% url 'something:sunita' %}">sunita's Page</a>
    </center>
</body>
</html>

templates/sunita.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hi anita....How r u</h1>
        <h1>When r u cmg to home</h1>
        <a href="{% url 'nothing:anita' %}">anita's Page</a>
    </center>
</body>
</html>